server:
  port: 8888

logging:
  file:
    path: logs
    name: userManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/course
    username: course
    password: course

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*